/*
 * ToDo List API
 *
 * API for managing a simple ToDo list.
 *
 * API version: 1.0.0
 * Contact: nevin.muhammad@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CreateOrUpdateToDo struct {
	Title string `json:"title"`
	Description string `json:"description,omitempty"`
	DueDate time.Time `json:"dueDate"`
	Priority string `json:"priority"`
	Status string `json:"status"`
	Tags []string `json:"tags,omitempty"`
}
