/*
 * ToDo List API
 *
 * API for managing a simple ToDo list.
 *
 * API version: 1.0.0
 * Contact: nevin.muhammad@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse404 struct {
	Error_ string `json:"error,omitempty"`
}
