/*
 * ToDo List API
 *
 * API for managing a simple ToDo list.
 *
 * API version: 1.0.0
 * Contact: nevin.muhammad@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type InlineResponse200 struct {
	Id string `json:"id,omitempty"`
	Title string `json:"title,omitempty"`
	Description string `json:"description,omitempty"`
	DueDate time.Time `json:"dueDate,omitempty"`
	Priority string `json:"priority,omitempty"`
	Status string `json:"status,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
