/*
 * ToDo List API
 * API for managing a simple ToDo list.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nevin.muhammad@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Todolist from './Todolist';

/**
 * The ArrayTodo model module.
 * @module model/ArrayTodo
 * @version 1.0.0
 */
export default class ArrayTodo extends Array {
  /**
   * Constructs a new <code>ArrayTodo</code>.
   * @alias module:model/ArrayTodo
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>ArrayTodo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArrayTodo} obj Optional instance to populate.
   * @return {module:model/ArrayTodo} The populated <code>ArrayTodo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ArrayTodo();
      ApiClient.constructFromObject(data, obj, 'Todolist');
    }
    return obj;
  }
}
