/*
 * ToDo List API
 * API for managing a simple ToDo list.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nevin.muhammad@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreateOrUpdateToDo model module.
 * @module model/CreateOrUpdateToDo
 * @version 1.0.0
 */
export default class CreateOrUpdateToDo {
  /**
   * Constructs a new <code>CreateOrUpdateToDo</code>.
   * @alias module:model/CreateOrUpdateToDo
   * @class
   * @param title {String} 
   * @param dueDate {Date} 
   * @param priority {module:model/CreateOrUpdateToDo.PriorityEnum} 
   * @param status {module:model/CreateOrUpdateToDo.StatusEnum} 
   */
  constructor(title, dueDate, priority, status) {
    this.title = title;
    this.dueDate = dueDate;
    this.priority = priority;
    this.status = status;
  }

  /**
   * Constructs a <code>CreateOrUpdateToDo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateOrUpdateToDo} obj Optional instance to populate.
   * @return {module:model/CreateOrUpdateToDo} The populated <code>CreateOrUpdateToDo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateOrUpdateToDo();
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('dueDate'))
        obj.dueDate = ApiClient.convertToType(data['dueDate'], 'Date');
      if (data.hasOwnProperty('priority'))
        obj.priority = ApiClient.convertToType(data['priority'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} title
 */
CreateOrUpdateToDo.prototype.title = undefined;

/**
 * @member {String} description
 */
CreateOrUpdateToDo.prototype.description = undefined;

/**
 * @member {Date} dueDate
 */
CreateOrUpdateToDo.prototype.dueDate = undefined;

/**
 * Allowed values for the <code>priority</code> property.
 * @enum {String}
 * @readonly
 */
CreateOrUpdateToDo.PriorityEnum = {
  /**
   * value: "low"
   * @const
   */
  low: "low",

  /**
   * value: "medium"
   * @const
   */
  medium: "medium",

  /**
   * value: "high"
   * @const
   */
  high: "high"
};
/**
 * @member {module:model/CreateOrUpdateToDo.PriorityEnum} priority
 * @default 'medium'
 */
CreateOrUpdateToDo.prototype.priority = 'medium';

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
CreateOrUpdateToDo.StatusEnum = {
  /**
   * value: "pending"
   * @const
   */
  pending: "pending",

  /**
   * value: "completed"
   * @const
   */
  completed: "completed"
};
/**
 * @member {module:model/CreateOrUpdateToDo.StatusEnum} status
 * @default 'pending'
 */
CreateOrUpdateToDo.prototype.status = 'pending';

/**
 * @member {Array.<String>} tags
 */
CreateOrUpdateToDo.prototype.tags = undefined;

