/*
 * ToDo List API
 * API for managing a simple ToDo list.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nevin.muhammad@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InlineResponse204 model module.
 * @module model/InlineResponse204
 * @version 1.0.0
 */
export default class InlineResponse204 {
  /**
   * Constructs a new <code>InlineResponse204</code>.
   * @alias module:model/InlineResponse204
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse204</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse204} obj Optional instance to populate.
   * @return {module:model/InlineResponse204} The populated <code>InlineResponse204</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse204();
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} success
 */
InlineResponse204.prototype.success = undefined;

