/*
 * ToDo List API
 * API for managing a simple ToDo list.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nevin.muhammad@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ArrayTodo from '../model/ArrayTodo';
import CreateOrUpdateToDo from '../model/CreateOrUpdateToDo';
import InlineResponse200 from '../model/InlineResponse200';
import InlineResponse204 from '../model/InlineResponse204';
import InlineResponse400 from '../model/InlineResponse400';
import InlineResponse404 from '../model/InlineResponse404';
import Todolist from '../model/Todolist';

/**
* Todolist service.
* @module api/TodolistApi
* @version 1.0.0
*/
export default class TodolistApi {

    /**
    * Constructs a new TodolistApi. 
    * @alias module:api/TodolistApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the todosGet operation.
     * @callback moduleapi/TodolistApi~todosGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArrayTodo{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all ToDo items
     * Only return active ToDo items, unless query param &#x27;status&#x27; is set to &#x27;all&#x27;
     * @param {Object} opts Optional parameters
     * @param {String} opts.title Filter ToDo items by title
     * @param {module:model/String} opts.status Filter ToDo items by status (default to <.>)
     * @param {module:api/TodolistApi~todosGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    todosGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'title': opts['title'],'status': opts['status']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['TodolistAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ArrayTodo;

      return this.apiClient.callApi(
        '/todos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the todosIdDelete operation.
     * @callback moduleapi/TodolistApi~todosIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse204{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a ToDo item by ID
     * @param {String} id ID of the ToDo item
     * @param {module:api/TodolistApi~todosIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    todosIdDelete(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling todosIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['TodolistAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse204;

      return this.apiClient.callApi(
        '/todos/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the todosIdGet operation.
     * @callback moduleapi/TodolistApi~todosIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse200{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a ToDo item by ID
     * Returns a single ToDo item by its ID, 404 if not found
     * @param {String} id ID of the ToDo item
     * @param {module:api/TodolistApi~todosIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    todosIdGet(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling todosIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['TodolistAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse200;

      return this.apiClient.callApi(
        '/todos/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the todosIdPut operation.
     * @callback moduleapi/TodolistApi~todosIdPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Todolist{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a ToDo item by ID
     * Updates an existing ToDo item with the provided details
     * @param {module:model/CreateOrUpdateToDo} body 
     * @param {String} id ID of the ToDo item
     * @param {module:api/TodolistApi~todosIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    todosIdPut(body, id, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling todosIdPut");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling todosIdPut");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['TodolistAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Todolist;

      return this.apiClient.callApi(
        '/todos/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the todosPost operation.
     * @callback moduleapi/TodolistApi~todosPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Todolist{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new ToDo item
     * Creates a new ToDo item with the provided details
     * @param {module:model/CreateOrUpdateToDo} body 
     * @param {module:api/TodolistApi~todosPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    todosPost(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling todosPost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['TodolistAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Todolist;

      return this.apiClient.callApi(
        '/todos', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}