# coding: utf-8

"""
    ToDo List API

    API for managing a simple ToDo list.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: nevin.muhammad@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="ToDo List API",
    author_email="nevin.muhammad@gmail.com",
    url="",
    keywords=["Swagger", "ToDo List API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    API for managing a simple ToDo list.  # noqa: E501
    """
)
