# coding: utf-8

"""
    ToDo List API

    API for managing a simple ToDo list.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: nevin.muhammad@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response204 import InlineResponse204  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse204(unittest.TestCase):
    """InlineResponse204 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse204(self):
        """Test InlineResponse204"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response204.InlineResponse204()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
