# coding: utf-8

"""
    ToDo List API

    API for managing a simple ToDo list.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: nevin.muhammad@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.todolist_api import TodolistApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTodolistApi(unittest.TestCase):
    """TodolistApi unit test stubs"""

    def setUp(self):
        self.api = TodolistApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_todos_get(self):
        """Test case for todos_get

        Get all ToDo items  # noqa: E501
        """
        pass

    def test_todos_id_delete(self):
        """Test case for todos_id_delete

        Delete a ToDo item by ID  # noqa: E501
        """
        pass

    def test_todos_id_get(self):
        """Test case for todos_id_get

        Get a ToDo item by ID  # noqa: E501
        """
        pass

    def test_todos_id_put(self):
        """Test case for todos_id_put

        Update a ToDo item by ID  # noqa: E501
        """
        pass

    def test_todos_post(self):
        """Test case for todos_post

        Create a new ToDo item  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
