/*
 * ToDo List API
 * API for managing a simple ToDo list.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nevin.muhammad@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ToDoListApi);
  }
}(this, function(expect, ToDoListApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ToDoListApi.TodolistApi();
  });

  describe('(package)', function() {
    describe('TodolistApi', function() {
      describe('todosGet', function() {
        it('should call todosGet successfully', function(done) {
          // TODO: uncomment, update parameter values for todosGet call and complete the assertions
          /*
          var opts = {};

          instance.todosGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ToDoListApi.ArrayTodo);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('todosIdDelete', function() {
        it('should call todosIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for todosIdDelete call and complete the assertions
          /*

          instance.todosIdDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ToDoListApi.InlineResponse204);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('todosIdGet', function() {
        it('should call todosIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for todosIdGet call and complete the assertions
          /*

          instance.todosIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ToDoListApi.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('todosIdPut', function() {
        it('should call todosIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for todosIdPut call and complete the assertions
          /*

          instance.todosIdPut(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ToDoListApi.Todolist);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('todosPost', function() {
        it('should call todosPost successfully', function(done) {
          // TODO: uncomment, update parameter values for todosPost call and complete the assertions
          /*

          instance.todosPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ToDoListApi.Todolist);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
